backend:
  name: git-gateway
  branch: main
  repo: fjsantel/MERCADOCONDELL

# Site configuration
site_url: https://fjsantel.github.io/MERCADOCONDELL
display_url: https://fjsantel.github.io/MERCADOCONDELL

# Configuración de archivos
media_folder: "assets" # Media files stored in the assets folder
public_folder: "/assets" # The src attribute for uploaded media

# Configuración de colecciones
collections:
  - name: "configuracion"
    label: "Configuración del Sitio"
    files:
      - name: "general"
        label: "Configuración General"
        file: "data/config.yml"
        fields:
          - {label: "Título del Sitio", name: "titulo", widget: "string"}
          - {label: "Descripción", name: "descripcion", widget: "text"}
          - {label: "URL del Sitio", name: "url", widget: "string"}
          - {label: "Email de Contacto", name: "email", widget: "string"}
          
      - name: "negocios_data"
        label: "Editar Negocios"
        file: "data/negocios.json" 
        fields:
          - name: "negocios"
            label: "Lista de Negocios del Mercado"
            widget: "list"
            summary: "{{fields.numero}}. {{fields.nombre}} ({{fields.categoria}})"
            fields:
              - {label: "Número", name: "numero", widget: "number", min: 1, max: 50}
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Categoría", name: "categoria", widget: "select", options: ["alimentos", "ropa", "musica", "decoracion", "cultura", "artesanias", "tecnologia", "belleza", "juguetes", "hogar", "servicios"]}
              - {label: "Descripción", name: "descripcion", widget: "text", rows: 4}

# Configuración de autenticación y permisos
# publish_mode: editorial_workflow # Disabled for direct publishing
show_preview_links: true

# Configuración del editor
slug:
  encoding: "ascii"
  clean_accents: true