backend:
  name: git-gateway
  branch: main
  repo: fjsantel/MERCADOCONDELL

# Site configuration
site_url: https://mercadocondell.netlify.app
display_url: https://mercadocondell.netlify.app

# Configuración de archivos
media_folder: "assets" # Media files stored in the assets folder
public_folder: "/assets" # The src attribute for uploaded media

# Configuración de colecciones
collections:
  - name: "configuracion"
    label: "Configuración del Sitio"
    files:
      - name: "general"
        label: "Configuración General"
        file: "_data/config.yml"
        fields:
          - {label: "Título del Sitio", name: "titulo", widget: "string"}
          - {label: "Descripción", name: "descripcion", widget: "text"}
          - {label: "URL del Sitio", name: "url", widget: "string"}
          - {label: "Email de Contacto", name: "email", widget: "string"}
          
      - name: "negocios_data"
        label: "Editar Negocios"
        file: "_data/negocios.json" 
        fields:
          - name: "negocios"
            label: "Lista de Negocios del Mercado"
            widget: "list"
            summary: "{{fields.numero}}. {{fields.nombre}} ({{fields.categoria}})"
            fields:
              - {label: "Número", name: "numero", widget: "number", min: 1, max: 50}
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Categoría", name: "categoria", widget: "select", options: ["alimentos", "ropa", "musica", "decoracion", "cultura", "artesanias", "tecnologia", "belleza", "juguetes", "hogar", "servicios"]}
              - {label: "Descripción", name: "descripcion", widget: "text", rows: 4}
              - {label: "Instagram", name: "instagram", widget: "string", required: false, hint: "URL completa de Instagram (ej: https://instagram.com/usuario)"}
              - {label: "Sitio Web", name: "website", widget: "string", required: false, hint: "URL completa del sitio web (ej: https://www.sitio.com)"}
              - {label: "WhatsApp", name: "whatsapp", widget: "string", required: false, hint: "Número de WhatsApp con código de país sin + (ej: 56912345678)"}

# Configuración de autenticación y permisos
# publish_mode: editorial_workflow # Disabled for direct publishing
show_preview_links: true

# Configuración del editor
slug:
  encoding: "ascii"
  clean_accents: true